version: "3"

services:
  redis:
    image: redis:alpine

  frontend:
    image: hulluukko/frontend
    ports:
      - 5000:5000

  backend:
    image: hulluukko/backend
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
